version: 2.1
jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8
    steps:
      - checkout
      - run: git submodule update --init
      - run: git submodule update --init --recursive --remote
      - run: mvn clean install -DskipTests=true
      #- run: chmod 777 ./build.sh
      #- run: ./build.sh
      #- store_artifacts:
          #path: 
workflows:
  version: 2.1
  workflow:
    jobs:
      - build
